version: "3.9"
services:
  app:
    container_name: pdf
    image: pdf
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile 
      target: base
      network: host
    ports:
      - 4000:4000
    volumes:
      - ./app/uploads/:/usr/var/app/uploads
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "dev2.gigadados.com.br:127.0.0.1"
      - "dev.gigadados.com.br:127.0.0.1"

